-- таблица пользователей
CREATE TABLE IF NOT EXISTS users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  name VARCHAR(255) NOT NULL,
  email VARCHAR(512) NOT NULL,
  CONSTRAINT pk_user PRIMARY KEY (id),
  CONSTRAINT UQ_USER_EMAIL UNIQUE (email)
);

-- таблица вещей
CREATE TABLE IF NOT EXISTS items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  name VARCHAR(256) NOT NULL,
  description VARCHAR(256) NOT NULL,
  owner_id BIGINT NOT NULL,
  available BOOLEAN NOT NULL,
  count_of_rent BIGINT NOT NULL DEFAULT 0,
  last_booking TIMESTAMP,
  next_booking TIMESTAMP,
  CONSTRAINT pk_item PRIMARY KEY (id),
  CONSTRAINT fk_items_owner FOREIGN KEY (owner_id) REFERENCES users(id)
);

-- таблица отзывов
CREATE TABLE IF NOT EXISTS comments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    item_id BIGINT NOT NULL,
    author_id BIGINT NOT NULL,
    text VARCHAR(512) NOT NULL,
    created TIMESTAMP NOT NULL,
    CONSTRAINT pk_comments PRIMARY KEY (id),
    CONSTRAINT fk_comments_to_item FOREIGN KEY (item_id) REFERENCES items(id),
    CONSTRAINT fk_comments_to_user FOREIGN KEY (author_id) REFERENCES users(id)
);

-- таблица запросов вещей
CREATE TABLE IF NOT EXISTS request_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  description VARCHAR(512) NOT NULL,
  created TIMESTAMP NOT NULL,
  user_id BIGINT NOT NULL,
  CONSTRAINT pk_request_items PRIMARY KEY (id),
  CONSTRAINT fk_request_items_to_user FOREIGN KEY (user_id) REFERENCES users(id)
);

-- таблица бронирования вещей
CREATE TABLE IF NOT EXISTS bookings (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  start_date TIMESTAMP NOT NULL,
  end_date TIMESTAMP NOT NULL,
  status VARCHAR(8) NOT NULL,
  item_id BIGINT NOT NULL,
  booker_id BIGINT NOT NULL,
  CONSTRAINT pk_booking PRIMARY KEY (id),
  CONSTRAINT fk_booking_item FOREIGN KEY (item_id) REFERENCES items(id),
  CONSTRAINT fk_booking_user FOREIGN KEY (booker_id) REFERENCES users(id)
);

-- таблица ответов на запросы
CREATE TABLE IF NOT EXISTS request_responses (
    request_id BIGINT NOT NULL,
    item_id BIGINT NOT NULL,
    CONSTRAINT pk_request_responses PRIMARY KEY (request_id, item_id),
    CONSTRAINT fk_request_responses_to_request FOREIGN KEY (request_id) REFERENCES request_items(id),
    CONSTRAINT fk_request_responses_to_item FOREIGN KEY (item_id) REFERENCES items(id)
);
